# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/gradle-scopes
    
    docker:
      # specify the version you desire here
      - image: timbru31/java-node 
    
    steps:
    
      - checkout
      - run: npm install -g yarn
      - run: yarn
      - run: bash <(curl -s https://copilot.blackducksoftware.com/ci/circle/scripts/upload)
